name: Gif Comment
on:
  issues: 
    types: [opened]
  
jobs:
  commment:
    if: 
    runs-on: ubuntu-latest
    steps:
      - name: Add funny comment
        uses: Marta83/funny-comment-action@v2.1
        id: FunnyComment
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITPHY_TOKEN: ${{ secrets.GIPHY_TOKEN }}
          comment_type: 'gif'
